services:
  dair-airlines:
    image: animosa04/dair_airlines:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-database;Database=DAir;User Id=sa;Password=DAirAirlines123!;Trusted_Connection=False;Encrypt=False;
      - ConnectionStrings__MongoDb=mongodb://mongo-database:27017
      - Serilog__WriteTo__0__Name=MongoDB
      - Serilog__WriteTo__0__Args__databaseUrl=mongodb://mongo-database:27017/DAirLogs
      - Serilog__WriteTo__0__Args__collectionName=Logs 
      - Serilog__WriteTo__0__Args__restrictedToMinimumLevel=Warning
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql-database
      - mongo-database

  sql-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: DAirAirlines123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  mongo-database:
    image: mongo:latest
    ports:
      - "27017:27017"